version: 2

models:
    - name: loan_streams
      description: "activity schema model on loans defaulted by customers"
      columns:
          - name: activity_id
            description: "The primary key and activity identifier for this table"
            tests:
                - unique
                - not_null

          - name: ts 
            description: 'timestamp of event: when loan was defaulted on'
            meta:
              dimension:
                type: timestamp
                time_intervals:  ['RAW', 'DAY', 'WEEK', 'MONTH', 'YEAR']

          - name: customer
            description: 'id of customer engaged in loan'
            meta:
              metrics:
                type: count

          - name: activity
            meta:
              dimension: 
                type: string

          - name: revenue_impact
            description: 'actual metric amount of loans'
            meta:
              metrics:
                total_revenue:
                  label: 'total revenue (usd)'
                  type: sum
                  round: 2
                  format: 'usd'
                
                average_revenue:
                  label: 'average revenue'
                  type: average
                  round: 2
                  format: 'usd'

          - name: activity_occurence
            description: 'how many times activity was repeated'
            meta:
              dimension:
                type: number

          - name: activity_repeated_at
            description: 'timestamp of when activity is/was repeated'
            meta:
              dimension:
                type: timestamp
                time_intervals:  ['RAW', 'DAY', 'WEEK', 'MONTH', 'YEAR']

    - name: loans_payments_ongoing
      description: "activity schema model on loan payments ongoing by customers"
      columns:
          - name: anonymous_customer_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
          
          - name: ts 
            description: 'timestamp of event: when loan is still in process of being paid'
            meta:
              dimension:
                type: timestamp
                time_intervals:  ['RAW', 'DAY', 'WEEK', 'MONTH', 'YEAR']

          - name: activity
            description: 'type of activity'
            meta:
              dimension: 
                type: string

          - name: revenue_impact
            description: 'actual metric amount of loans'
            meta:
              metrics:
                total_revenue:
                  label: 'total revenue (usd)'
                  type: sum
                  round: 2
                  format: 'usd'

          - name: activity_occurence
            description: 'how many times activity was repeated'
            meta:
              dimension:
                type: number

          - name: activity_repeated_at
            description: 'timestamp of when activity is/was repeated'
            meta:
              dimension:
                type: timestamp
                time_intervals:  ['RAW', 'DAY', 'WEEK', 'MONTH', 'YEAR']

    - name: loans_payments_repaid
      description: "activity schema mode on loans repaid by customers"
      columns:
        - name: activity_id

        - name: ts 
          description: 'timestamp of event: when loan was repaid in full'
          meta:
              dimension:
                type: timestamp
                time_intervals:  ['RAW', 'DAY', 'WEEK', 'MONTH', 'YEAR']

        - name: activity
          description: 'type of activity'
          meta:
              dimension: 
                type: string

        - name: revenue_impact
          description: 'actual metric amount of loans'
          meta:
              metrics:
                total_revenue:
                  label: 'total revenue (usd)'
                  type: sum
                  round: 2
                  format: 'usd'

        - name: activity_occurence
          description: 'how many times activity was repeated'
          meta:
              dimension:
                type: number

        - name: activity_repeated_at
          description: 'timestamp of when activity is/was repeated'
          meta:
              dimension:
                type: timestamp
                time_intervals:  ['RAW', 'DAY', 'WEEK', 'MONTH', 'YEAR']
         